apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: lb-static-ips #  IP addresses for services
      protocol: layer2
      addresses:
      - 192.168.49.2-192.168.49.2
