apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: default
  annotations:           # <-- Which IP pool to use
    metallb.universe.tf/address-pool: lb-static-ips
spec:
  type: LoadBalancer
  selector:
    name: mosquitto
  ports:
    - name: mosquitto
      protocol: TCP
      port: 1883
      targetPort: 1883