apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-configmap
  namespace: default
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    protocol mqtt
    persistence true
    persistence_location /mosquitto/data
    log_dest stdout